<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8vsnMq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8vsnMq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8vsnMq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8vsnMq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV8vsnMq\App_KernelDevDebugContainer([
    'container.build_hash' => 'V8vsnMq',
    'container.build_id' => '2d77a17c',
    'container.build_time' => 1740985575,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8vsnMq');
