<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKaMbOb3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKaMbOb3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKaMbOb3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKaMbOb3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKaMbOb3\App_KernelDevDebugContainer([
    'container.build_hash' => 'KaMbOb3',
    'container.build_id' => '82bae334',
    'container.build_time' => 1741084037,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKaMbOb3');
